// Autocomplete module for finding places
var autocompleteNS = (function ($) {
    'use strict';

    /* Class properties */

    // Internal class properties
	var _map;
    // var _icons;
	
    return {

		/** Attaches autocomplete functionality to the input element
		 * Options is an object with these properties:
		 * source is either a static list of data, or function that returns a list (e.g. via ajax) of results. Each result should have at least these properties: label, value, desc
		 * select is a callback that takes a filtered result as arg, and can be run for side effects such as setting a marker on a map
		 * renderItem is a callback for rendering the menu items, it takes as arguments the menu element and item and should return a rendered list item.
		*  Items are rendered by default with the label on a first line, and a smaller font description on the second.
		*/
		addTo: function (map, inputElement, options) {
			
			// Global the map object
			_map = map;
			
			// Default options
		    if (typeof(options) == "undefined") {
				options = {};
		    }
		
		    // Default options to the source url
		    if (typeof(options) == "string") {
				options = {sourceUrl: options};
		    }
		
		    // Default to geocoder function
		    if (typeof(options.source) == "undefined") {
				options.source = function (request, response) {autocompleteNS.geocoderAjax (options.sourceUrl, request, response);}
			}
		
			// If there is a map on the page then default to centering on the selection
		    if (typeof(options.select) == "undefined") {
		
				// Select callback - centres map on selection
				options.select = this.centreMap;
			}
		
		    // Default function for rendering the menu
		    if (typeof(options.renderItem) == "undefined") {
		
				// Default render over two lines, second line smaller font size
				options.renderItem = function( ul, item ) {
					    return $( "<li>" )
							.append( "<a>" + item.label + "<br><span style=\"font-size:smaller\">" + item.desc + "</span></a>" )
							.appendTo( ul );
					}
		    }
		
		
			// Run on document ready
		    $(function() {
		
				// Add the autocomplete to the element
				$( inputElement )
		
					.autocomplete({
						source: options.source,
						minLength: 3,
						focus: function( event, ui ) {
							// This is called when the selected menu item changes.
							// Reflect the value of the time in the input box.
							$( inputElement ).val( ui.item.label );
		
							// Stop propagation
							// Canceling this event prevents the value from being updated, but does not prevent the menu item from being focused.
							return false;
						},
		
					select: function( event, ui ) {
		
								// Apply any select callback
								if(typeof(options.select) != "undefined") {
									return options.select (ui.item);
								}
		
								// Set the value
							    $( inputElement ).val( ui.item.label );
		
							    // Stop propagation - which would set the value of the inputElement to the ui.item.value
				    			return false;
							}
			    	})
					.data( "ui-autocomplete" )._renderItem = options.renderItem;
		    })
		},
		
		
		// Centres map on lon lat in the autocomplete result.
		// Equipped to handle CycleStreets standard uses of both OpenLayers and Leaflet
		centreMap: function (result) {
		
			// OpenLayers map
			if (typeof(CS) != "undefined" && typeof(CS.map) != "undefined") {
		
				// Set the centre
				CS.focusLonLat(result.lon, result.lat);
		
				// Exit
				return;
			}
		
			// Leaflet
			if (typeof(map) != "undefined") {
		
				// Zoom to at least 16
				var zoomTo = _map.getZoom() < 16 ? 16 : _map.getZoom();
		
				// Set the centre
				_map.setView([result.lat, result.lon], zoomTo);
			}
		},
		
		
		// Function used to retrieve results from a Nominatim server
		geocoderAjax: function (url, request, response) {
		
		    // Query string arguments for the Nominatim call
		    var urlParams = {
				format: "json",
				// addressdetails: 1,
				polygon_geojson: 1,
				q: request.term
		    };
		
			// If there is a map on the page then assume it will provide bounds
			if ($("#map")) {
		
				// Bounded search
				urlParams.bounded = 1;
		
				// Callback that returns a csv: <left>,<top>,<right>,<bottom>
				urlParams.viewbox = autocompleteNS.mapBoundsCallBack();
		    };
		
		    $.ajax({
				url: url,
		
				// The next two options configure jQuery to parse the jsonp returned by call
				dataType: "jsonp",
				// Nominatim supports the value of this parameter which wraps json output in a callback function.
				// The callback function name is generated by jQuery, and parses the json.
				jsonp: "json_callback",
		
				data: urlParams,
				
				// On success run returned data through a filter
				success: function ( data, textStatus, jqXHR ) {
			    	response ( $.map( data, autocompleteNS.filterNominatimResult));
				},
		
				// Autocomplete needs to call response() even when an error occurs to avoid falling into an invalid state.
				error: function ( jqXHR, textStatus, errorThrown ) {
		
			    	// By using these values the user can see an error has occured
				    response ([{
					value: errorThrown,
					label: "An error occured: " + textStatus,
					desc: "Error type: " + errorThrown}]);
				},
		
				// Handle some http error codes
				statusCode: {
			    	404: function() {
						alert( "The name lookup service cannot be found" );
				    }
				}
		    });
		},
		
		
		// Bounds callback - retrieves current viewport of map.
		// Equipped to handle CycleStreets standard uses of both OpenLayers and Leaflet
		mapBoundsCallBack: function () {
		
			// OpenLayers map
		    if (typeof(CS) !== "undefined" && typeof(CS.map) !== "undefined") {
		
				// Convert bounds to lon/lat
				var bounds = CS.map.getExtent().transform(CS.map.getProjectionObject(), CS.map.displayProjection);
				return bounds.left + "," + bounds.top + "," + bounds.right + "," + bounds.bottom;
			}
		
			// Leaflet
		    if (typeof(_map) !== "undefined") {
				var bounds = _map.getBounds();
		
				// Unfortunately cannot use toBBoxString() because that returns WSEN
				return bounds.getSouthWest().lng + "," + bounds.getNorthEast().lat + "," + bounds.getNorthEast().lng + "," + bounds.getSouthWest().lat;
			}
		},
		
		
		// Used to process each result from the nominatim
		filterNominatimResult: function (item) {
		
		    // Extract the street and neighbourhood
		    var sn = autocompleteNS.streetNeighbourhood (item.display_name);
		
			//
			var result = {
				// The display_name is used as the full value for the widget because feeding it back into the query seems to be the best way of getting a repeatable result.
				value: item.display_name,
				label: sn.street,
				desc: sn.neighbourhood,
				lat: item.lat,
				lon: item.lon
		    }
		
			// Optional geojson
		    if (typeof(item.geojson) != "undefined") {result.geojson = item.geojson;}
		
		    // Result
		    return result;
		},
		
				
		// The display_name contains a comma separated address, usually very comprehensive.
		// The user only needs to know the right level of detail in the given context.
		// If addressdetails are requested the result contains those details - but not in a consistent pattern and so cannot be easily selected.
		streetNeighbourhood: function (display_name) {
		
			// Set defaults
			var street = "Unknown street";
			var neighbourhood = "Unknown neighbourhood";
		
			// Use display_name which is usually a full address
			if (typeof display_name != "undefined") {
		
				// Disassemble display name
				var nameComponents = display_name.split(", ");
		
				// When there are plenty of components
				if (nameComponents.length >= 4) {
		
					// Use the first couple of bits for the street
					street = nameComponents[0] + ", " + nameComponents[1];
		
					// Use the next couple of bits for the neighbourhood
					neighbourhood = nameComponents[2] + ", " + nameComponents[3];
		
				} else if (nameComponents.length >= 2) {
		
					// Use the first bit for the street
					street = nameComponents.shift();
		
					// Use the rest for the neighbourhood
					neighbourhood = nameComponents.join(", ");
		
				} else {
		
					// Use all of it for the street
					street = display_name;
				}
			}
		
			// Result
			return {"street": street, "neighbourhood": neighbourhood}
		}

    };

}) (jQuery);